// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
<<<<<<< HEAD
import { defineConfig } from "prisma/config";
=======
import { defineConfig, env } from "prisma/config";
>>>>>>> 37770fa3ef31f035f4517cb371066a8425473d5e

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
<<<<<<< HEAD
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
=======
    path: "prisma/migrations"
  },
  datasource: {
    url: env("DATABASE_URL")
  }
>>>>>>> 37770fa3ef31f035f4517cb371066a8425473d5e
});
