import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  'pt-BR': {
    navHome: 'Início', navHow: 'Como funciona', navMap: 'Mapa', navFeed: 'Feed', navAbout: 'Sobre', navContact: 'Contato',
    login: 'Entrar', logout: 'Sair', account: 'Minha conta', accountSettings: 'Configurações da conta', siteSettings: 'Configurações do site', createProfile: 'Criar novo perfil', createAccount: 'Criar conta',
    language: 'Idioma', portuguese: 'Português (Brasil)', english: 'English', spanish: 'Español',
    liveMap: 'Mapa vivo da cidade', citySpeaks: 'A CIDADE', speaks: 'FALA', amplify: 'Você amplifica',
    heroCopy: 'Reporte buracos, lixo, iluminação, árvores e outros problemas urbanos com mapa interativo, votação comunitária e acompanhamento real.',
    openMap: 'Abrir mapa', exploreMap: 'Explorar mapa', livePanel: 'Painel ao vivo', online: 'Online', cityFocus: 'Cidade em foco', recentCases: 'Ocorrências recentes', live: 'Ao vivo',
    reportProblem: 'Reportar um problema', reportDescription: 'Abra o formulário e envie localização, foto e descrição.', openMapAction: 'Abrir o mapa', mapDescription: 'Veja os pontos já cadastrados e clique nos marcadores.', enterAccount: 'Entrar na conta', accountDescription: 'Acesse o histórico, votos e perfil do usuário.', cityFlow: 'Fluxo da cidade', flowOne: 'Você identifica o problema e envia o local com rapidez.', flowTwo: 'O ponto entra no mapa com categoria e status visual.', flowThree: 'A comunidade vota e acompanha a resolução do caso.',
    feedCases: 'Casos no feed', connectedCities: 'Cidades conectadas', collectiveSupport: 'Apoio coletivo',
    flow: 'Fluxo', howItWorks: 'Como funciona?', howDescription: 'Uma experiência simples: registrar, localizar e acompanhar a melhoria.', takePhoto: 'Tire uma foto', takePhotoDescription: 'Registre o problema com contexto visual para acelerar a triagem.', locateProblem: 'Localize o problema', locateDescription: 'Marque o ponto exato no mapa para facilitar a mobilização.', trackResolution: 'Acompanhe a resolução', trackDescription: 'Veja quando o caso mudar de status e avance no acompanhamento.',
    recentIdentifications: 'Identificações recentes', seeAllMap: 'Ver tudo no mapa', loadingProblems: 'Carregando problemas...', noProblems: 'Nenhum problema encontrado no momento.',
    context: 'Contexto', together: 'JUNTOS, PODEMOS TRANSFORMAR A NOSSA CIDADE', contextDescription: 'A plataforma conecta relato, mapa e acompanhamento em um fluxo direto, sem ruído visual.', quickAccess: 'Acesso rápido', about: 'Sobre', whatIs: 'O que é?', aboutDescription: 'O Voz Urbana é uma plataforma para facilitar a comunicação entre população e órgãos públicos, permitindo denúncias práticas e acompanhamento do status de cada caso.', platformInUse: 'A plataforma em uso', mapLabel: 'Mapa', mapDescriptionShort: 'Marcadores reais com popups, fit bounds e visual escuro.', reports: 'Relatórios', reportsDescription: 'Criação de ocorrências com categoria, localização e acompanhamento.', contactTitle: 'Fale com a Voz Urbana', sendMessage: 'Enviar mensagem', whatsapp: 'WhatsApp', phone: 'Telefone', email: 'E-mail',
    allStatuses: 'Todos os status', allCategories: 'Todas as categorias',
    loginTitle: 'Entrar na sua conta', password: 'Senha', emailPlaceholder: 'seu@email.com', passwordPlaceholder: 'Sua senha', loginLoading: 'Entrando...', noAccount: 'Não tem conta?', signUp: 'Cadastre-se', loginSuccess: 'Login bem-sucedido!', loginError: 'Erro ao fazer login',
    registerTitle: 'Criar conta', name: 'Nome', fullNamePlaceholder: 'Seu nome completo', username: 'Nome de usuário', usernameHint: 'Use de 3 a 30 caracteres: letras, números, ponto ou sublinhado.', passwordConfirm: 'Confirme a senha', confirmPasswordPlaceholder: 'Confirme sua senha', minPassword: 'Mínimo 6 caracteres', registerLoading: 'Criando conta...', hasAccount: 'Já tem conta?', signIn: 'Faça login', passwordMismatch: 'As senhas não coincidem', registerSuccess: 'Cadastro realizado! Verifique seu e-mail para confirmar a conta.', registerError: 'Erro ao cadastrar',
    verifyTitle: 'Verificação de e-mail', verifyLoading: 'Validando seu link...', verifyPrompt: 'Abra o link enviado para o seu e-mail para confirmar a conta.', registeredEmail: 'E-mail cadastrado', resend: 'Reenviar e-mail de confirmação', resending: 'Reenviando...', resendSuccess: 'Enviamos um novo link de confirmação. Confira sua caixa de entrada e o spam.', verifyError: 'Não foi possível verificar o e-mail.', resendError: 'Não foi possível reenviar o e-mail.', goToLogin: 'Ir para o login',
    loadingPosts: 'Carregando publicações...', noPosts: 'Nenhuma publicação encontrada.', comment: 'Comentar', now: 'agora', publications: 'publicação(ões)', previous: 'Anterior', next: 'Próxima', page: 'Página', refreshFeed: 'Atualizar feed', noCategory: 'Sem categoria', locationOnMap: 'Localização informada no mapa', openStatus: 'Abertos', progressStatus: 'Em andamento', resolvedStatus: 'Resolvidos', rejectedStatus: 'Rejeitados',
    mapProblems: 'Mapa de problemas', mapIntro: 'Sua voz melhora a cidade. Reporte problemas urbanos e acompanhe soluções.', drawingArea: 'Desenhando área...', selectArea: 'Selecionar área no mapa', clearArea: 'Limpar área', clear: 'Limpar', finishArea: 'Finalizar área', drawing: 'Desenho', areaInstruction: 'Clique em pelo menos', areaInProgress: 'Área em desenho com', selectedArea: 'Área selecionada com', filters: 'Filtros', status: 'Status', category: 'Categoria', sort: 'Ordenar', recent: 'Mais recentes', mostVoted: 'Mais votados', startDate: 'Data inicial', endDate: 'Data final', radius: 'Raio de distância', selectCategory: 'Selecione uma categoria', occurrences: 'ocorrência(s)', clearSelection: 'Limpar seleção', clickMarker: 'Clique em um marcador do mapa para ver os detalhes aqui.', demoMode: 'Modo demonstração ativado, a API não respondeu',
    notifications: 'Notificações', markAllRead: 'Ler todas', noNotifications: 'Nenhuma notificação', openProblem: 'Abrir problema', locationNotSpecified: 'Local não especificado', noMapPoints: 'Nenhum ponto disponível no mapa', mapEmptyHint: 'Cadastre um problema para ver os marcadores aqui', feedFallback: 'Os dados vêm da API. Quando ela não responde, a página continua viva com os registros de demonstração.', mapSectionIntro: 'Clique em um marcador para destacar o problema abaixo do mapa.', activeCategories: 'Categorias ativas', legend: 'Legenda compacta para leitura rápida', clickMarkerShort: 'Clique em um marcador para ver os detalhes aqui', after: 'Depois', before: 'Antes', update: 'Atualização',
    problemReport: 'Reportar problema', reportIntro: 'Ajude a melhorar a cidade reportando um problema urbano', required: 'obrigatório', loadingCategories: 'Carregando categorias...', problemTitle: 'Título do problema', problemTitlePlaceholder: 'Ex: Buraco na rua principal', detailedDescription: 'Descrição detalhada', descriptionPlaceholder: 'Descreva o problema em detalhes...', address: 'Endereço', addressPlaceholder: 'Rua, número, bairro...', mapLocation: 'Localização no mapa', mapLocationHint: 'Clique no mapa ou arraste o marcador para ajustar o local.', imagesOptional: 'Imagens (opcional)', latitude: 'Latitude', longitude: 'Longitude', reportLoading: 'Reportando...', reportSuccess: 'Problema reportado com sucesso!', reportError: 'Erro ao reportar problema', requiredFields: 'Preencha todos os campos obrigatórios',
    profile: 'Meu perfil', saveProfile: 'Salvar perfil', saving: 'Salvando...', accountEmail: 'E-mail', bio: 'Bio', role: 'Papel', profilePhoto: 'Foto de perfil', removePhoto: 'Remover foto', zoom: 'Zoom', profileUpdated: 'Perfil atualizado com sucesso!', profileError: 'Erro ao atualizar perfil',
    adminDashboard: 'Painel administrativo', adminError: 'Erro ao carregar estatísticas', totalProblems: 'Total de problemas', users: 'Usuários', categories: 'Categorias', summary: 'Resumo', toResolve: 'Problemas a resolver',
    problemNotFound: 'Problema não encontrado', loading: 'Carregando...', reportedBy: 'Reportado por', date: 'Data', support: 'Apoiar', whatDoYouThink: 'O que acha dessa denúncia?', comments: 'Comentários', writeComment: 'Escreva uma atualização ou comentário', noComments: 'Ainda não há comentários.', updates: 'Atualizações', loginToVote: 'Faça login para votar', loginToComment: 'Faça login para comentar', voteRegistered: 'Voto registrado!', commentPublished: 'Comentário publicado', points: 'pontos', selectedProblem: 'Problema selecionado',
  },
  en: {
    navHome: 'Home', navHow: 'How it works', navMap: 'Map', navFeed: 'Feed', navAbout: 'About', navContact: 'Contact',
    login: 'Log in', logout: 'Log out', account: 'My account', accountSettings: 'Account settings', siteSettings: 'Site settings', createProfile: 'Create new profile', createAccount: 'Create account',
    language: 'Language', portuguese: 'Português (Brasil)', english: 'English', spanish: 'Español',
    liveMap: 'Live city map', citySpeaks: 'THE CITY', speaks: 'SPEAKS', amplify: 'You amplify',
    heroCopy: 'Report potholes, trash, lighting, trees and other urban problems with an interactive map, community voting and real follow-up.',
    openMap: 'Open map', exploreMap: 'Explore map', livePanel: 'Live panel', online: 'Online', cityFocus: 'City focus', recentCases: 'Recent reports', live: 'Live',
    reportProblem: 'Report a problem', reportDescription: 'Open the form and send the location, photo and description.', openMapAction: 'Open the map', mapDescription: 'See registered points and click the markers.', enterAccount: 'Log in', accountDescription: 'Access your history, votes and profile.', cityFlow: 'City flow', flowOne: 'Identify the problem and send its location quickly.', flowTwo: 'The point enters the map with category and visual status.', flowThree: 'The community votes and follows the resolution.',
    feedCases: 'Feed cases', connectedCities: 'Connected cities', collectiveSupport: 'Collective support',
    flow: 'Flow', howItWorks: 'How does it work?', howDescription: 'A simple experience: report, locate and follow improvements.', takePhoto: 'Take a photo', takePhotoDescription: 'Record the problem with visual context to speed up triage.', locateProblem: 'Locate the problem', locateDescription: 'Mark the exact point on the map to mobilize people.', trackResolution: 'Track the resolution', trackDescription: 'See when the case status changes and follow its progress.',
    recentIdentifications: 'Recent reports', seeAllMap: 'See everything on the map', loadingProblems: 'Loading problems...', noProblems: 'No problems found at the moment.',
    context: 'Context', together: 'TOGETHER, WE CAN TRANSFORM OUR CITY', contextDescription: 'The platform connects reports, maps and follow-up in a direct, clear flow.', quickAccess: 'Quick access', about: 'About', whatIs: 'What is it?', aboutDescription: 'Voz Urbana facilitates communication between residents and public agencies through practical reports and status tracking.', platformInUse: 'The platform in use', mapLabel: 'Map', mapDescriptionShort: 'Real markers with popups, fit bounds and a dark visual.', reports: 'Reports', reportsDescription: 'Create reports with category, location and follow-up.', contactTitle: 'Talk to Voz Urbana', sendMessage: 'Send message', whatsapp: 'WhatsApp', phone: 'Phone', email: 'Email',
    allStatuses: 'All statuses', allCategories: 'All categories',
    loginTitle: 'Log in to your account', password: 'Password', emailPlaceholder: 'you@email.com', passwordPlaceholder: 'Your password', loginLoading: 'Signing in...', noAccount: "Don't have an account?", signUp: 'Sign up', loginSuccess: 'Login successful!', loginError: 'Login failed',
    registerTitle: 'Create account', name: 'Name', fullNamePlaceholder: 'Your full name', username: 'Username', usernameHint: 'Use 3 to 30 characters: letters, numbers, period or underscore.', passwordConfirm: 'Confirm password', confirmPasswordPlaceholder: 'Confirm your password', minPassword: 'Minimum 6 characters', registerLoading: 'Creating account...', hasAccount: 'Already have an account?', signIn: 'Log in', passwordMismatch: 'Passwords do not match', registerSuccess: 'Account created! Check your email to confirm it.', registerError: 'Registration failed',
    verifyTitle: 'Email verification', verifyLoading: 'Validating your link...', verifyPrompt: 'Open the link sent to your email to confirm your account.', registeredEmail: 'Registered email', resend: 'Resend confirmation email', resending: 'Resending...', resendSuccess: 'A new confirmation link was sent. Check your inbox and spam folder.', verifyError: 'Could not verify the email.', resendError: 'Could not resend the email.', goToLogin: 'Go to login',
    loadingPosts: 'Loading posts...', noPosts: 'No posts found.', comment: 'Comment', now: 'now', publications: 'publication(s)', previous: 'Previous', next: 'Next', page: 'Page', refreshFeed: 'Refresh feed', noCategory: 'No category', locationOnMap: 'Location provided on the map', openStatus: 'Open', progressStatus: 'In progress', resolvedStatus: 'Resolved', rejectedStatus: 'Rejected',
    mapProblems: 'Problem map', mapIntro: 'Your voice improves the city. Report urban problems and follow solutions.', drawingArea: 'Drawing area...', selectArea: 'Select area on map', clearArea: 'Clear area', clear: 'Clear', finishArea: 'Finish area', drawing: 'Drawing', areaInstruction: 'Click at least', areaInProgress: 'Area being drawn with', selectedArea: 'Area selected with', filters: 'Filters', status: 'Status', category: 'Category', sort: 'Sort', recent: 'Most recent', mostVoted: 'Most voted', startDate: 'Start date', endDate: 'End date', radius: 'Distance radius', selectCategory: 'Select a category', occurrences: 'report(s)', clearSelection: 'Clear selection', clickMarker: 'Click a map marker to see details here.', demoMode: 'Demo mode enabled, the API did not respond',
    notifications: 'Notifications', markAllRead: 'Mark all as read', noNotifications: 'No notifications', openProblem: 'Open problem', locationNotSpecified: 'Location not specified', noMapPoints: 'No points available on the map', mapEmptyHint: 'Create a report to see markers here', feedFallback: 'Data comes from the API. When it does not respond, the page remains active with demo records.', mapSectionIntro: 'Click a marker to highlight the problem below the map.', activeCategories: 'Active categories', legend: 'Compact legend for quick reading', clickMarkerShort: 'Click a marker to see details here', after: 'After', before: 'Before', update: 'Update',
    problemReport: 'Report problem', reportIntro: 'Help improve the city by reporting an urban problem', required: 'required', loadingCategories: 'Loading categories...', problemTitle: 'Problem title', problemTitlePlaceholder: 'E.g. Pothole on the main street', detailedDescription: 'Detailed description', descriptionPlaceholder: 'Describe the problem in detail...', address: 'Address', addressPlaceholder: 'Street, number, neighborhood...', mapLocation: 'Location on map', mapLocationHint: 'Click the map or drag the marker to adjust the location.', imagesOptional: 'Images (optional)', latitude: 'Latitude', longitude: 'Longitude', reportLoading: 'Reporting...', reportSuccess: 'Problem reported successfully!', reportError: 'Error reporting problem', requiredFields: 'Fill in all required fields',
    profile: 'My profile', saveProfile: 'Save profile', saving: 'Saving...', accountEmail: 'Email', bio: 'Bio', role: 'Role', profilePhoto: 'Profile photo', removePhoto: 'Remove photo', zoom: 'Zoom', profileUpdated: 'Profile updated successfully!', profileError: 'Error updating profile',
    adminDashboard: 'Admin dashboard', adminError: 'Error loading statistics', totalProblems: 'Total problems', users: 'Users', categories: 'Categories', summary: 'Summary', toResolve: 'Problems to resolve',
    problemNotFound: 'Problem not found', loading: 'Loading...', reportedBy: 'Reported by', date: 'Date', support: 'Support', whatDoYouThink: 'What do you think about this report?', comments: 'Comments', writeComment: 'Write an update or comment', noComments: 'No comments yet.', updates: 'Updates', loginToVote: 'Log in to vote', loginToComment: 'Log in to comment', voteRegistered: 'Vote registered!', commentPublished: 'Comment published', points: 'points', selectedProblem: 'Selected problem',
  },
  es: {
    navHome: 'Inicio', navHow: 'Cómo funciona', navMap: 'Mapa', navFeed: 'Feed', navAbout: 'Sobre nosotros', navContact: 'Contacto',
    login: 'Entrar', logout: 'Salir', account: 'Mi cuenta', accountSettings: 'Configuración de la cuenta', siteSettings: 'Configuración del sitio', createProfile: 'Crear nuevo perfil', createAccount: 'Crear cuenta',
    language: 'Idioma', portuguese: 'Português (Brasil)', english: 'English', spanish: 'Español',
    liveMap: 'Mapa vivo de la ciudad', citySpeaks: 'LA CIUDAD', speaks: 'HABLA', amplify: 'Tú amplificas',
    heroCopy: 'Reporta baches, basura, iluminación, árboles y otros problemas urbanos con mapa interactivo, votación comunitaria y seguimiento real.',
    openMap: 'Abrir mapa', exploreMap: 'Explorar mapa', livePanel: 'Panel en vivo', online: 'En línea', cityFocus: 'Ciudad en foco', recentCases: 'Casos recientes', live: 'En vivo',
    reportProblem: 'Reportar un problema', reportDescription: 'Abre el formulario y envía ubicación, foto y descripción.', openMapAction: 'Abrir el mapa', mapDescription: 'Mira los puntos registrados y haz clic en los marcadores.', enterAccount: 'Entrar a la cuenta', accountDescription: 'Accede a tu historial, votos y perfil.', cityFlow: 'Flujo de la ciudad', flowOne: 'Identifica el problema y envía su ubicación rápidamente.', flowTwo: 'El punto entra al mapa con categoría y estado visual.', flowThree: 'La comunidad vota y acompaña la solución.',
    feedCases: 'Casos en el feed', connectedCities: 'Ciudades conectadas', collectiveSupport: 'Apoyo colectivo',
    flow: 'Flujo', howItWorks: '¿Cómo funciona?', howDescription: 'Una experiencia simple: registrar, ubicar y acompañar la mejora.', takePhoto: 'Toma una foto', takePhotoDescription: 'Registra el problema con contexto visual para acelerar la revisión.', locateProblem: 'Ubica el problema', locateDescription: 'Marca el punto exacto en el mapa para facilitar la movilización.', trackResolution: 'Acompaña la solución', trackDescription: 'Mira cuándo cambia el estado y sigue el avance.',
    recentIdentifications: 'Identificaciones recientes', seeAllMap: 'Ver todo en el mapa', loadingProblems: 'Cargando problemas...', noProblems: 'No se encontraron problemas.',
    context: 'Contexto', together: 'JUNTOS, PODEMOS TRANSFORMAR NUESTRA CIUDAD', contextDescription: 'La plataforma conecta reportes, mapa y seguimiento en un flujo directo y claro.', quickAccess: 'Acceso rápido', about: 'Sobre nosotros', whatIs: '¿Qué es?', aboutDescription: 'Voz Urbana facilita la comunicación entre la población y los organismos públicos mediante reportes prácticos y seguimiento de estados.', platformInUse: 'La plataforma en uso', mapLabel: 'Mapa', mapDescriptionShort: 'Marcadores reales con popups y visual oscuro.', reports: 'Reportes', reportsDescription: 'Crea casos con categoría, ubicación y seguimiento.', contactTitle: 'Habla con Voz Urbana', sendMessage: 'Enviar mensaje', whatsapp: 'WhatsApp', phone: 'Teléfono', email: 'Correo electrónico',
    allStatuses: 'Todos los estados', allCategories: 'Todas las categorías',
    loginTitle: 'Entrar a tu cuenta', password: 'Contraseña', emailPlaceholder: 'tu@email.com', passwordPlaceholder: 'Tu contraseña', loginLoading: 'Entrando...', noAccount: '¿No tienes cuenta?', signUp: 'Crear cuenta', loginSuccess: '¡Inicio de sesión exitoso!', loginError: 'Error al iniciar sesión',
    registerTitle: 'Crear cuenta', name: 'Nombre', fullNamePlaceholder: 'Tu nombre completo', username: 'Nombre de usuario', usernameHint: 'Usa de 3 a 30 caracteres: letras, números, punto o guion bajo.', passwordConfirm: 'Confirmar contraseña', confirmPasswordPlaceholder: 'Confirma tu contraseña', minPassword: 'Mínimo 6 caracteres', registerLoading: 'Creando cuenta...', hasAccount: '¿Ya tienes cuenta?', signIn: 'Inicia sesión', passwordMismatch: 'Las contraseñas no coinciden', registerSuccess: '¡Cuenta creada! Revisa tu correo para confirmar la cuenta.', registerError: 'Error al registrarse',
    verifyTitle: 'Verificación de correo', verifyLoading: 'Validando tu enlace...', verifyPrompt: 'Abre el enlace enviado a tu correo para confirmar la cuenta.', registeredEmail: 'Correo registrado', resend: 'Reenviar correo de confirmación', resending: 'Reenviando...', resendSuccess: 'Enviamos un nuevo enlace de confirmación. Revisa tu bandeja y el spam.', verifyError: 'No se pudo verificar el correo.', resendError: 'No se pudo reenviar el correo.', goToLogin: 'Ir al inicio de sesión',
    loadingPosts: 'Cargando publicaciones...', noPosts: 'No se encontraron publicaciones.', comment: 'Comentar', now: 'ahora', publications: 'publicación(es)', previous: 'Anterior', next: 'Siguiente', page: 'Página', refreshFeed: 'Actualizar feed', noCategory: 'Sin categoría', locationOnMap: 'Ubicación indicada en el mapa', openStatus: 'Abiertos', progressStatus: 'En progreso', resolvedStatus: 'Resueltos', rejectedStatus: 'Rechazados',
    mapProblems: 'Mapa de problemas', mapIntro: 'Tu voz mejora la ciudad. Reporta problemas urbanos y acompaña las soluciones.', drawingArea: 'Dibujando área...', selectArea: 'Seleccionar área en el mapa', clearArea: 'Limpiar área', clear: 'Limpiar', finishArea: 'Finalizar área', drawing: 'Dibujo', areaInstruction: 'Haz clic en al menos', areaInProgress: 'Área en dibujo con', selectedArea: 'Área seleccionada con', filters: 'Filtros', status: 'Estado', category: 'Categoría', sort: 'Ordenar', recent: 'Más recientes', mostVoted: 'Más votados', startDate: 'Fecha inicial', endDate: 'Fecha final', radius: 'Radio de distancia', selectCategory: 'Selecciona una categoría', occurrences: 'ocurrencia(s)', clearSelection: 'Limpiar selección', clickMarker: 'Haz clic en un marcador del mapa para ver los detalles aquí.', demoMode: 'Modo demostración activado, la API no respondió',
    notifications: 'Notificaciones', markAllRead: 'Marcar todas como leídas', noNotifications: 'Ninguna notificación', openProblem: 'Abrir problema', locationNotSpecified: 'Ubicación no especificada', noMapPoints: 'No hay puntos disponibles en el mapa', mapEmptyHint: 'Crea un reporte para ver los marcadores aquí', feedFallback: 'Los datos vienen de la API. Cuando no responde, la página sigue activa con registros de demostración.', mapSectionIntro: 'Haz clic en un marcador para destacar el problema debajo del mapa.', activeCategories: 'Categorías activas', legend: 'Leyenda compacta para lectura rápida', clickMarkerShort: 'Haz clic en un marcador para ver los detalles aquí', after: 'Después', before: 'Antes', update: 'Actualización',
    problemReport: 'Reportar problema', reportIntro: 'Ayuda a mejorar la ciudad reportando un problema urbano', required: 'obligatorio', loadingCategories: 'Cargando categorías...', problemTitle: 'Título del problema', problemTitlePlaceholder: 'Ej: Bache en la calle principal', detailedDescription: 'Descripción detallada', descriptionPlaceholder: 'Describe el problema en detalle...', address: 'Dirección', addressPlaceholder: 'Calle, número, barrio...', mapLocation: 'Ubicación en el mapa', mapLocationHint: 'Haz clic en el mapa o arrastra el marcador para ajustar el lugar.', imagesOptional: 'Imágenes (opcional)', latitude: 'Latitud', longitude: 'Longitud', reportLoading: 'Reportando...', reportSuccess: '¡Problema reportado con éxito!', reportError: 'Error al reportar problema', requiredFields: 'Completa todos los campos obligatorios',
    profile: 'Mi perfil', saveProfile: 'Guardar perfil', saving: 'Guardando...', accountEmail: 'Correo electrónico', bio: 'Biografía', role: 'Rol', profilePhoto: 'Foto de perfil', removePhoto: 'Eliminar foto', zoom: 'Zoom', profileUpdated: '¡Perfil actualizado!', profileError: 'Error al actualizar el perfil',
    adminDashboard: 'Panel administrativo', adminError: 'Error al cargar estadísticas', totalProblems: 'Total de problemas', users: 'Usuarios', categories: 'Categorías', summary: 'Resumen', toResolve: 'Problemas por resolver',
    problemNotFound: 'Problema no encontrado', loading: 'Cargando...', reportedBy: 'Reportado por', date: 'Fecha', support: 'Apoyar', whatDoYouThink: '¿Qué opinas de este reporte?', comments: 'Comentarios', writeComment: 'Escribe una actualización o comentario', noComments: 'Aún no hay comentarios.', updates: 'Actualizaciones', loginToVote: 'Inicia sesión para votar', loginToComment: 'Inicia sesión para comentar', voteRegistered: '¡Voto registrado!', commentPublished: '¡Comentario publicado!', points: 'puntos', selectedProblem: 'Problema seleccionado',
  },
};

const I18nContext = createContext(null);

export const I18nProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'pt-BR');
  const value = useMemo(() => ({ language, setLanguage, t: (key) => translations[language]?.[key] || translations['pt-BR'][key] || key }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
};

export const useI18n = () => useContext(I18nContext);
